[env:nucleo_f401re]
platform = ststm32
board = nucleo_f401re
framework = arduino
lib_deps =
    sandeepmistry/LoRa@0.8.0
    hideakitai/MPU9250@0.4.8
    adafruit/DHT sensor library@1.4.7
    adafruit/Adafruit Unified Sensor@1.1.15
monitor_speed = 115200
