[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
    hideakitai/MPU9250@0.4.8
    adafruit/DHT sensor library@1.4.7
    adafruit/Adafruit Unified Sensor@1.1.15
    sandeepmistry/LoRa@0.8.0
monitor_speed = 9600
monitor_port = 
